modal_width: 860
id_field: id

fields:
  - type: section
    label: Allgemein
    cols: 2

  - name: description
    type: text
    label: Name
    max: 50
    required: true

  - name: type
    type: select
    label: Typ
    required: true
    options:
      - value: intern
        label: Intern
      - value: extern
        label: Extern

  - name: enabled
    type: boolean
    label: Aktiviert

  - type: section
    label: Quelle
    cols: 2

  - name: source_remote_id
    type: select
    label: Server
    options_endpoint: /api/remotes/for-select?type=rsync
    required: true

  - name: source_path
    type: text
    label: Pfad
    max: 200
    required: true

  - type: section
    label: Ziel
    cols: 2

  - name: target_remote_id
    type: select
    label: Server
    options_endpoint: /api/remotes/for-select?type=rsync
    required: true

  - name: target_path
    type: text
    label: Pfad
    max: 200
    required: true
