id_field: id
fields:
  - name: description
    type: text
    label: Beschreibung
    max: 50
    column: 1
    row: 1
    required: true
  - name: enabled
    type: boolean
    label: Aktiviert
    column: 2
    row: 1
  - name: vmid
    type: number
    label: Container-ID
    column: 1
    row: 2
  - name: node
    type: text
    label: Node
    max: 50
    column: 2
    row: 2
