modal_width: 860
id_field: id

fields:
  - name: description
    type: text
    label: Name
    max: 50
    required: true

  - name: enabled
    type: boolean
    label: Aktiviert

  - type: section
    label: Quelle
    cols: 1

  - name: source_remote_id
    type: select
    label: Source Server
    options_endpoint: /api/remotes/for-select?type=borg
    required: true

  - name: source_path
    type: text
    label: Source Path
    max: 200
    required: true

  - type: section
    label: Ziel
    cols: 1

  - name: target_remote_id
    type: select
    label: Target Server
    options_endpoint: /api/remotes/for-select?type=borg
    required: false

  - name: target_path
    type: text
    label: Target Path
    max: 200

  - type: section
    label: Skripte & Filter
    cols: 3

  - name: pre
    type: list
    label: Pre-Script

  - name: post
    type: list
    label: Post-Script

  - name: exclude
    type: list
    label: Exclude-Patterns
