modal_width: 560

fields:
  - key: rsync_delete
    label: Delete
    type: checkbox
    checkbox_label: Dateien im Ziel löschen, die in der Quelle nicht mehr vorhanden sind
    default: true

  - key: rsync_compress
    label: Komprimierung
    type: checkbox
    checkbox_label: Daten während der Übertragung komprimieren
    default: false
