test:
  enabled: false
  description: "Firewall borg backup"
  source_host: local
  source_path: /tmp/backup
  target_host: local
  target_path: /storage/borg/firewall
  pre: 
    - "mkdir -p /tmp/backup"
    - "cd /tmp/backup"
    - "touch testfile.txt"
  post: 
    - "rm -rf /tmp/backup"

firewall:
  enabled: true
  description: "Firewall borg backup"
  source_host: local
  source_path: /tmp/backup
  target_host: local
  target_path: /storage/borg/firewall
  pre: 
    - "mkdir -p /tmp/backup"
    - "scp -o BatchMode=yes -o ConnectTimeout=10 backupadm@172.19.0.201:/conf/config.xml /tmp/backup/firewall01.xml"
    - "scp -o BatchMode=yes -o ConnectTimeout=10 backupadm@172.19.0.202:/conf/config.xml /tmp/backup/firewall02.xml"
  post: 
    - "rm -rf /tmp/backup"

dms:
  enabled: true
  description: "DMS borg backup"
  source_host: dms.simpsons.lan
  source_path: /tmp/backup
  target_host: backup01.simpsons.lan
  target_path: /storage/borg/dms
  ssh_user: "paperless"
  pre: 
    - "mkdir -p /tmp/backup"
    - "cd ~ "
    - "source .venv/bin/activate"
    - "cd src"
    - "python3 manage.py document_exporter /tmp/backup"
  post: 
    - "rm -rf /tmp/backup"

cloud:  
  enabled: true
  description: "Cloud borg backup"
  source_host: nextcloud.simpsons.lan
  source_path: /backup
  target_host: backup01.simpsons.lan
  target_path: /storage/borg/cloud
  pre: 
    - "sudo -u www-data /usr/bin/php /var/www/nextcloud/occ maintenance:mode --on"
    - "sudo systemctl stop nginx"
    - "sudo mount -o bind /storage /backup/files"
    - "PGPASSWORD=\"nextcloud\" pg_dump nextcloud -h localhost -U nextcloud -f /backup/database/nextcloud-sqlbkp_`date +\"%Y%m%d\"`.bak"
  post: 
    - "sudo umount /backup/files"
    - "rm -rf /backup/database/*"
    - "sudo systemctl start nginx"
    - "sudo -u www-data /usr/bin/php /var/www/nextcloud/occ maintenance:mode --off"

music:
  enabled: true
  description: "Music borg backup"
  source_host: nfs.simpsons.lan
  source_path: /storage/music
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/music

series:
  enabled: true
  description: "Series borg backup"
  source_host: nfs.simpsons.lan
  source_path: /storage/video/series
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/series

comedy:
  enabled: true
  description: "Comedy borg backup"
  source_host: nfs.simpsons.lan
  source_path: /storage/video/comedy
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/comedy

concerts:
  enabled: true
  description: "Concerts borg backup"
  source_host: nfs.simpsons.lan
  source_path: /storage/video/concerts
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/concerts

family:
  enabled: true
  description: "Family borg backup"
  source_host: nfs.simpsons.lan
  source_path: /storage/video/family
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/family

movies:
  enabled: true
  description: "Movies borg backup"
  source_host: nfs.simpsons.lan
  source_path: /storage/video/movies
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/movies