2:
  enabled: true
  description: firewall01 & firewall021
  source_host: local
  source_path: /tmp/backup
  target_host: local
  target_path: /storage/borg/firewall
  pre:
  - mkdir -p /tmp/backup
  - scp -o BatchMode=yes -o ConnectTimeout=10 backupadm@172.19.0.201:/conf/config.xml
    /tmp/backup/firewall01.xml
  - scp -o BatchMode=yes -o ConnectTimeout=10 backupadm@172.19.0.202:/conf/config.xml
    /tmp/backup/firewall02.xml
  post:
  - rm -rf /tmp/backup
3:
  enabled: true
  description: dms.simpsons.lan
  source_host: dms.simpsons.lan
  source_path: /tmp/backup
  target_host: backup01.simpsons.lan
  target_path: /storage/borg/dms
  ssh_user: paperless
  pre:
  - mkdir -p /tmp/backup
  - 'cd ~ '
  - source .venv/bin/activate
  - cd src
  - python3 manage.py document_exporter /tmp/backup
  post:
  - rm -rf /tmp/backup
4:
  enabled: true
  description: nextcloud.simpsons.lan
  source_host: nextcloud.simpsons.lan
  source_path: /backup
  target_host: backup01.simpsons.lan
  target_path: /storage/borg/cloud
  pre:
  - sudo -u www-data /usr/bin/php /var/www/nextcloud/occ maintenance:mode --on
  - sudo systemctl stop nginx
  - sudo mount -o bind /storage /backup/files
  - PGPASSWORD="nextcloud" pg_dump nextcloud -h localhost -U nextcloud -f /backup/database/nextcloud-sqlbkp_`date
    +"%Y%m%d"`.bak
  post:
  - sudo umount /backup/files
  - rm -rf /backup/database/*
  - sudo systemctl start nginx
  - sudo -u www-data /usr/bin/php /var/www/nextcloud/occ maintenance:mode --off
5:
  enabled: true
  description: Music auf nfs.simpsons.lan
  source_host: nfs.simpsons.lan
  source_path: /storage/music
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/music
6:
  enabled: true
  description: Series auf nfs.simpsons.lan
  source_host: nfs.simpsons.lan
  source_path: /storage/video/series
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/series
7:
  enabled: true
  description: Comedy auf nfs.simpsons.lan
  source_host: nfs.simpsons.lan
  source_path: /storage/video/comedy
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/comedy
8:
  enabled: true
  description: Concerts auf nfs.simpsons.lan
  source_host: nfs.simpsons.lan
  source_path: /storage/video/concerts
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/concerts
9:
  enabled: true
  description: Family auf nfs.simpsons.lan
  source_host: nfs.simpsons.lan
  source_path: /storage/video/family
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/family
10:
  enabled: true
  description: Movies auf nfs.simpsons.lan
  source_host: nfs.simpsons.lan
  source_path: /storage/video/movies
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/movies
11:
  enabled: true
  description: Kamera auf syncthing.simpsons.lan
  source_host: syncthing.simpsons.lan
  source_path: /storage/kamera
  target_host: backup01.simpsons.lan
  target_path: /storage/borg/kamera
  exclude:
  - '*/.stfolder*'
  - '*/.trashed*'
  - '*/.ttx*'
  - '*/thumbnails*'
