verify-storage-ct:
  enabled: false
  description: "Überprüfe Storage 'ct'"
  host: local
  type: verify

verify-storage-host:
  enabled: true
  description: "Überprüfe Storage 'host'"
  host: local
  type: verify

prune-storage-ct:
  enabled: false
  description: "Bereinige Storage 'ct'"
  host: local
  type: prune

prune-storage-host:
  enabled: true
  description: "Bereinige Storage 'host'"
  host: local
  type: prune

sync-storage-ct_backup02:
  enabled: true
  description: "Synchronisiere Storage 'ct'"
  host: backup02
  type: sync

sync-storage-host_backup02:
  enabled: true
  description: "Synchronisiere Storage 'host'"
  host: backup02
  type: sync

sync-extern-ct_backup02:
  enabled: false
  description: "Synchronisiere externen Storage 'ct'"
  host: backup02
  type: sync

sync-extern-host_backup02:
  enabled: false
  description: "Synchronisiere externen Storage 'host'"
  host: backup02
  type: sync

sync-storage-ct_backup03:
  enabled: true
  description: "Synchronisiere Storage 'ct'"
  host: backup03
  type: sync

sync-storage-host_backup03:
  enabled: true
  description: "Synchronisiere Storage 'host'"
  host: backup03
  type: sync
