jobs:
  verify:
    - enabled: true
      name: verify-storage-ct
      host: local

    - enabled: true
      name: verify-storage-host
      host: local

  prune:
    - enabled: true
      name: prune-storage-ct
      host: local

    - enabled: true
      name: prune-storage-host
      host: local

  sync:
    - enabled: true
      name: sync-storage-ct
      host: backup02

    - enabled: true
      name: sync-storage-host
      host: backup02

    - enabled: false
      name: sync-extern-ct
      host: backup02

    - enabled: false
      name: sync-extern-host
      host: backup02

    - enabled: true
      name: sync-storage-ct
      host: backup03

    - enabled: true
      name: sync-storage-host
      host: backup03

lxc:
  1001:
    name: intranet
    node: proxmox01
    enabled: true

  1002:
    name: password
    node: proxmox01
    enabled: true

  1003:
    name: ntfy
    node: proxmox01
    enabled: true

  1004:
    name: dms
    node: proxmox02
    enabled: true

  1005:
    name: wiki
    node: proxmox02
    enabled: true

  1006:
    name: adguard
    node: proxmox03
    enabled: true

  1007:
    name: syncthing
    node: proxmox02
    enabled: true

  1008:
    name: ldap
    node: proxmox01
    enabled: true

  1009:
    name: streaming
    node: proxmox03
    enabled: true

  1011:
    name: nextcloud
    node: proxmox03
    enabled: true

  1012:
    name: nfs
    node: proxmox03
    enabled: true

  1013:
    name: mirror
    node: proxmox03
    enabled: true

  1014:
    name: aur
    node: proxmox03
    enabled: true

  1015:
    name: influxdb
    node: proxmox03
    enabled: true

  1016:
    name: grafana
    node: proxmox03
    enabled: true

  1017:
    name: postgresql
    node: proxmox03
    enabled: true

  1018:
    name: admin
    node: proxmox01
    enabled: true

  1019:
    name: mosquitto
    node: proxmox03
    enabled: true

  1020:
    name: zigbee2mqtt
    node: proxmox03
    enabled: true

  1021:
    name: ha
    node: proxmox03
    enabled: true

  1023:
    name: apt
    node: proxmox02
    enabled: true

  1025:
    name: packages
    node: proxmox01
    enabled: true

  9004:
    name: dms-test
    node: proxmox03
    enabled: true

host:
  proxmox01:
    enabled: true
    source:
      - "cluster.pxar:/var/lib/pve-cluster"
  proxmox02:
    enabled: true
    source:
      - "cluster.pxar:/var/lib/pve-cluster"
  proxmox03:
    enabled: true
    source:
      - "cluster.pxar:/var/lib/pve-cluster"
  local:
    enabled: true
    source:
      - "backupadm.pxar:/var/lib/backupadm"
  backup02:
    enabled: true         
  backup03:
    enabled: true
  vpn:
    enabled: true
  nfs01:
    enabled: true
  nfs02:
    enabled: true