1:
  host: proxmox01
  description: proxmox01.simpsons.lan
  enabled: true
  source:
  - cluster.pxar:/var/lib/pve-cluster
2:
  host: proxmox02
  description: proxmox02.simpsons.lan
  enabled: true
  source:
  - cluster.pxar:/var/lib/pve-cluster
3:
  host: proxmox03
  description: proxmox03.simpsons.lan
  enabled: true
  source:
  - cluster.pxar:/var/lib/pve-cluster
4:
  host: local
  description: backup01.simpsons.lan
  enabled: true
  source:
  - backupadm.pxar:/var/lib/backupadm
5:
  host: backup02
  description: backup02.simpsons.lan
  enabled: true
6:
  host: backup03
  description: backup03.simpsons.lan
  enabled: true
7:
  host: vpn
  description: vpn.simpsons.lan
  enabled: true
8:
  description: test rsync
  enabled: false
