1:
  job: verify-storage-ct
  enabled: false
  description: Überprüfe Storage 'ct'
  host: local
  type: verify
2:
  job: verify-storage-host
  enabled: true
  description: Überprüfe Storage 'host'
  host: local
  type: verify
3:
  job: prune-storage-ct
  enabled: true
  description: Bereinige Storage 'ct'
  host: local
  type: prune
4:
  job: prune-storage-host
  enabled: true
  description: Bereinige Storage 'host'
  host: local
  type: prune
5:
  job: sync-storage-ct_backup02
  enabled: true
  description: Synchronisiere Storage 'ct'
  host: backup02
  type: sync
6:
  job: sync-storage-host_backup02
  enabled: true
  description: Synchronisiere Storage 'host'
  host: backup02
  type: sync
7:
  job: sync-extern-ct_backup02
  enabled: true
  description: Synchronisiere externen Storage 'ct'
  host: backup02
  type: sync
8:
  job: sync-extern-host_backup02
  enabled: true
  description: Synchronisiere externen Storage 'host'
  host: backup02
  type: sync
9:
  job: sync-storage-ct_backup03
  enabled: true
  description: Synchronisiere Storage 'ct'
  host: backup03
  type: sync
10:
  job: sync-storage-host_backup03
  enabled: true
  description: Synchronisiere Storage 'host'
  host: backup03
  type: sync
