1:
  enabled: true
  description: DMS → Backup02 Hauptspeicher
  source_host: local
  source_path: /storage/borg/dms/
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/dms/
2:
  enabled: true
  description: DMS → Backup02 externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/dms/
  target_host: local
  target_path: /storage_extern/borg/dms/
3:
  enabled: true
  description: DMS → Backup03 Hauptspeicher
  source_host: local
  source_path: /storage/borg/dms/
  target_host: backup03.simpsons.lan
  target_path: /storage/borg/dms/
4:
  enabled: true
  description: Firewall → Backup02 Hauptspeicher
  source_host: local
  source_path: /storage/borg/firewall/
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/firewall/
5:
  enabled: true
  description: Firewall → Backup02 externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/firewall/
  target_host: local
  target_path: /storage_extern/borg/firewall/
6:
  enabled: true
  description: Firewall → Backup03 Hauptspeicher
  source_host: local
  source_path: /storage/borg/firewall/
  target_host: backup03.simpsons.lan
  target_path: /storage/borg/firewall/
7:
  enabled: true
  description: Cloud → Backup02 Hauptspeicher
  source_host: local
  source_path: /storage/borg/cloud/
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/cloud/
8:
  enabled: true
  description: Cloud → Backup02 externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/cloud/
  target_host: local
  target_path: /storage_extern/borg/cloud/
9:
  enabled: true
  description: Cloud → Backup03 Hauptspeicher
  source_host: local
  source_path: /storage/borg/cloud/
  target_host: backup03.simpsons.lan
  target_path: /storage/borg/cloud/
10:
  enabled: true
  description: Kamera → Backup02 Hauptspeicher
  source_host: local
  source_path: /storage/borg/kamera/
  target_host: backup02.simpsons.lan
  target_path: /storage/borg/kamera/
11:
  enabled: true
  description: Kamera → Backup02 externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/kamera/
  target_host: local
  target_path: /storage_extern/borg/kamera/
12:
  enabled: true
  description: Kamera → Backup03 Hauptspeicher
  source_host: local
  source_path: /storage/borg/kamera/
  target_host: backup03.simpsons.lan
  target_path: /storage/borg/kamera/
13:
  enabled: true
  description: Family → lokales externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/family/
  target_host: local
  target_path: /storage_extern/borg/family/
14:
  enabled: true
  description: Comedy → lokales externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/comedy/
  target_host: local
  target_path: /storage_extern/borg/comedy/
15:
  enabled: true
  description: Concerts → lokales externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/concerts/
  target_host: local
  target_path: /storage_extern/borg/concerts/
16:
  enabled: true
  description: Movies → lokales externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/movies/
  target_host: local
  target_path: /storage_extern/borg/movies/
17:
  enabled: true
  description: Music → lokales externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/music/
  target_host: local
  target_path: /storage_extern/borg/music/
18:
  enabled: true
  description: Series → lokales externes Storage
  source_host: backup02.simpsons.lan
  source_path: /storage/borg/series/
  target_host: local
  target_path: /storage_extern/borg/series/
