id_field: id
fields:
  - name: type
    type: info
    label: Typ
    column: 1
    row: 1

  - name: enabled
    type: boolean
    label: Aktiviert
    column: 2
    row: 1

  - name: remote_id
    type: info
    label: Host
    resolve: remote_host
    column: 1
    row: 2

  - name: job
    type: info
    label: Job
    column: 2
    row: 2
