id_field: id
fields:
  - name: description
    type: info
    label: Beschreibung
    column: 1
    row: 1
  - name: vmid
    type: info
    label: Container-ID
    column: 2
    row: 1
  - name: node
    type: info
    label: Node
    resolve: remote_host
    column: 1
    row: 2
  - name: enabled
    type: boolean
    label: Aktiviert
    column: 2
    row: 2
